const path = require("path");
const fsUtils = require("../utils/filesystem");
const logger = require("../utils/logger");
const packageManager = require("../utils/package-manager");
const { exec } = require("child_process");
const util = require("util");
const execPromise = util.promisify(exec);

// Feature Generators
const routerGen = require("./router");
const tailwindGen = require("./tailwind");
const eslintGen = require("./eslint");
const stateGen = require("./state");
// const apiGen = require("./api");
// const formsGen = require("./forms");
// const validationGen = require("./validation");
// const testingGen = require("./testing");

const generate = async (config) => {
  const { projectName, targetPath, language, bundler, git } = config;
  const isTS = language === "typescript";

  logger.blank();
  const spinner = logger.spinner(`Creating project in ${targetPath}...`).start();

  try {
    // 1. Determine base template
    const templateName = `base-${bundler}-${isTS ? "ts" : "js"}`;
    const sourcePath = path.resolve(__dirname, "..", "templates", templateName);

    // Verify template exists (we will create these soon)
    if (!(await fsUtils.fileExists(sourcePath))) {
      spinner.fail(`Template ${templateName} not found.`);
      throw new Error(`Template not implemented yet: ${templateName}`);
    }

    // 2. Copy base template
    await fsUtils.ensureDir(targetPath);
    await fsUtils.copyTemplate(sourcePath, targetPath);

    // 3. Load package.json into memory
    const pkgPath = path.resolve(targetPath, "package.json");
    let pkg = { name: projectName, version: "0.1.0", private: true, scripts: {}, dependencies: {}, devDependencies: {} };
    if (await fsUtils.fileExists(pkgPath)) {
      pkg = { ...pkg, ...(await fsUtils.readJson(pkgPath)), name: projectName };
    }

    spinner.text = "Configuring features...";

    // 4. Run feature generators (to be implemented)
    await routerGen(config, targetPath, pkg);
    await tailwindGen(config, targetPath, pkg);
    await eslintGen(config, targetPath, pkg);
    await stateGen(config, targetPath, pkg);
    // await apiGen(config, targetPath, pkg);
    // await formsGen(config, targetPath, pkg);
    // await validationGen(config, targetPath, pkg);
    // await testingGen(config, targetPath, pkg);

    // Generate README.md
    await fsUtils.writeFile(
      path.resolve(targetPath, "README.md"),
      `# ${projectName}\n\nGenerated by [Namaste React](https://github.com/prahladinala/namaste-react).\n\n## Getting Started\n\n\`\`\`bash\nnpm install\n${bundler === "vite" ? "npm run dev" : "npm start"}\n\`\`\`\n`
    );

    // Generate Environment file
    await fsUtils.writeFile(path.resolve(targetPath, ".env.example"), "# Example Environment Variables\n");

    // 5. Write package.json back
    await fsUtils.writeJson(pkgPath, pkg);

    spinner.succeed("Generated project files");

    // 6. Install dependencies
    spinner.start("Installing dependencies (this might take a while)...");
    const pm = packageManager.detect();
    await packageManager.install(targetPath, pm);
    spinner.succeed("Installed dependencies");

    // 7. Initialize Git
    if (git) {
      spinner.start("Initializing Git repository...");
      try {
        await execPromise("git init", { cwd: targetPath });
        
        // Setup gitignore BEFORE adding files!
        const gitignorePath = path.resolve(targetPath, ".gitignore");
        if (!(await fsUtils.fileExists(gitignorePath))) {
          await fsUtils.writeFile(gitignorePath, "node_modules\n.DS_Store\ndist\nbuild\n.env\n");
        }

        await execPromise("git add .", { cwd: targetPath });

        spinner.succeed("Initialized Git repository");
      } catch (err) {
        spinner.fail("Failed to initialize Git repository (is Git installed?)");
      }
    }

  } catch (error) {
    spinner.fail("Project generation failed");
    throw error;
  }
};

module.exports = { generate };
